# Generated by Django 4.2.28 on 2026-02-24 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Número do Processo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Consulta')),
                ('dados_processo', models.JSONField(blank=True, null=True, verbose_name='Dados do Processo')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('analise_ia', models.TextField(blank=True, verbose_name='Análise da IA')),
                ('analise_atualizada_em', models.DateTimeField(blank=True, null=True)),
                ('processo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_tribunal', to='processos.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Consulta de Processo',
                'verbose_name_plural': 'Consultas de Processos',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Tribunal')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('tipo', models.CharField(choices=[('trabalho', 'Justiça do Trabalho'), ('federal', 'Justiça Federal'), ('estadual', 'Justiça Estadual'), ('eleitoral', 'Justiça Eleitoral'), ('militar', 'Justiça Militar')], max_length=50, verbose_name='Tipo')),
                ('regiao', models.CharField(blank=True, max_length=50, verbose_name='Região')),
                ('api_endpoint', models.URLField(verbose_name='Endpoint da API')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunais',
                'ordering': ['tipo', 'regiao'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da IA')),
                ('data_pergunta', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='consulta_tribunais.consultaprocesso', verbose_name='Consulta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta sobre Processo',
                'verbose_name_plural': 'Perguntas sobre Processos',
                'ordering': ['-data_pergunta'],
            },
        ),
        migrations.AddField(
            model_name='consultaprocesso',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consulta_tribunais.tribunal', verbose_name='Tribunal'),
        ),
        migrations.AddField(
            model_name='consultaprocesso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_tribunal', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='consultaprocesso',
            index=models.Index(fields=['numero_processo', 'tribunal'], name='consulta_tr_numero__5a730a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultaprocesso',
            index=models.Index(fields=['-data_consulta'], name='consulta_tr_data_co_ace475_idx'),
        ),
    ]
