# Generated by Django 6.0.2 on 2026-02-23 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiência'), ('prazo', 'Prazo Fatal'), ('reuniao', 'Reunião'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('alerta_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to='processos.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['data', 'hora'],
            },
        ),
    ]
