# Generated by Django 6.0.2 on 2026-02-23 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
            ],
            options={
                'verbose_name': 'Comarca',
                'verbose_name_plural': 'Comarcas',
                'ordering': ['estado', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número do Processo')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado'), ('arquivado', 'Arquivado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor da Causa (R$)')),
                ('objeto', models.TextField(verbose_name='Objeto / Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('advogado', models.ForeignKey(limit_choices_to={'papel__in': ['advogado', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.cliente', verbose_name='Cliente')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.tipoprocesso', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('documento', models.FileField(blank=True, null=True, upload_to='movimentacoes/', verbose_name='Documento Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Vara')),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varas', to='processos.comarca', verbose_name='Comarca')),
            ],
            options={
                'verbose_name': 'Vara',
                'verbose_name_plural': 'Varas',
                'ordering': ['comarca', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='vara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.vara', verbose_name='Vara'),
        ),
    ]
