# Generated by Django 4.2.28 on 2026-02-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='processos/arquivos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_processo_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Arquivo do Processo',
                'verbose_name_plural': 'Arquivos do Processo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
