# Generated by Django 4.2.28 on 2026-02-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0002_processoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='demanda',
            field=models.TextField(blank=True, null=True, verbose_name='Demanda do Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='processos_possiveis',
            field=models.ManyToManyField(blank=True, related_name='clientes_interessados', to='processos.tipoprocesso', verbose_name='Processos Possíveis'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.CreateModel(
            name='ClienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='clientes/arquivos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='processos.cliente', verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_cliente_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo do Cliente',
                'verbose_name_plural': 'Arquivos do Cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
