# Generated by Django 4.2.28 on 2026-02-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0002_cliente_bairro_cliente_complemento_cliente_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='conflito_interesses_observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Conflito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conflito_interesses_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status de Conflito de Interesses'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='formulario_qualificacao',
            field=models.JSONField(blank=True, null=True, verbose_name='Formulário de Qualificação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_campanha',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_etapa',
            field=models.CharField(choices=[('novo', 'Novo'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta'), ('contrato', 'Contrato'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=30, verbose_name='Etapa do Lead'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_origem',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Origem do Lead'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_lead_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável do Lead'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_sla_resposta_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA de Resposta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_ultimo_contato_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qualificacao_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score da Qualificação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qualificacao_status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_analise', 'Em Análise'), ('qualificado', 'Qualificado'), ('desqualificado', 'Desqualificado')], default='nao_iniciado', max_length=30, verbose_name='Status da Qualificação'),
        ),
        migrations.CreateModel(
            name='ClienteTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20, verbose_name='Prioridade')),
                ('prazo_em', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_cliente_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_cliente_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa de Cliente',
                'verbose_name_plural': 'Tarefas de Cliente',
                'ordering': ['status', 'prazo_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('contrato', 'Contrato'), ('procuracao', 'Procuração')], max_length=20, verbose_name='Tipo do Documento')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='clientes/contratos/', verbose_name='Arquivo')),
                ('status_assinatura', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('assinado', 'Assinado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status da Assinatura')),
                ('assinatura_provedor', models.CharField(blank=True, max_length=80, null=True, verbose_name='Provedor de Assinatura')),
                ('assinatura_envelope_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='Envelope ID')),
                ('assinatura_link', models.URLField(blank=True, null=True, verbose_name='Link de Assinatura')),
                ('assinado_em', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cliente_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Contrato de Cliente',
                'verbose_name_plural': 'Contratos de Cliente',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Canal')),
                ('tipo', models.CharField(choices=[('mensagem', 'Mensagem'), ('followup', 'Follow-up'), ('agendamento', 'Agendamento')], default='mensagem', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('agendado_em', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automacoes_cliente_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Automação de Cliente',
                'verbose_name_plural': 'Automações de Cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
