# Generated by Django 4.2.28 on 2026-02-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0006_processo_modulo_avancado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título')),
                ('tipo_peca', models.CharField(choices=[('defesa', 'Peça de Defesa'), ('recurso', 'Recurso'), ('peticao', 'Petição'), ('manifestacao', 'Manifestação'), ('outro', 'Outra Peça')], default='peticao', max_length=20, verbose_name='Tipo da Peça')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em Revisão'), ('finalizada', 'Finalizada'), ('protocolada', 'Protocolada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('ia_score_qualidade', models.PositiveSmallIntegerField(default=0, verbose_name='Score IA de Qualidade')),
                ('ia_revisao', models.JSONField(blank=True, null=True, verbose_name='Revisão IA')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_processo_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_processo_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Peça do Processo',
                'verbose_name_plural': 'Peças do Processo',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
