# Generated by Django 4.2.28 on 2026-02-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0007_processopeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='segredo_justica',
            field=models.BooleanField(default=False, verbose_name='Segredo de Justiça'),
        ),
        migrations.AlterField(
            model_name='processoresponsavel',
            name='papel',
            field=models.CharField(choices=[('principal', 'Principal'), ('apoio', 'Apoio'), ('estagiario', 'Estagiário'), ('assistente', 'Assistente')], default='apoio', max_length=20, verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='processoresponsavel',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'papel__in': ['advogado', 'administrador', 'estagiario', 'assistente']}, on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades_processo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='processotarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador', 'estagiario', 'assistente']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_processo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
