# Generated by Django 4.2.28 on 2026-02-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAtividadeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login_web', 'Login Web'), ('login_api', 'Login API'), ('logout', 'Logout'), ('gestao_usuarios', 'Acesso à Gestão de Usuários'), ('usuario_criado', 'Usuário Criado'), ('usuario_editado', 'Usuário Editado'), ('perfil_atualizado', 'Perfil Atualizado'), ('acesso_portal', 'Acesso ao Portal')], max_length=40, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('rota', models.CharField(blank=True, max_length=255, verbose_name='Rota')),
                ('ip_endereco', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('dados_extra', models.JSONField(blank=True, null=True, verbose_name='Dados Extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor da Ação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Referência')),
            ],
            options={
                'verbose_name': 'Log de Atividade de Usuário',
                'verbose_name_plural': 'Logs de Atividade de Usuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
