# Generated by Django 4.2.28 on 2026-02-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuarioatividadelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='responsavel_advogado',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('advogado', 'Advogado'), ('estagiario', 'Estagiário'), ('assistente', 'Assistente')], default='advogado', max_length=20, verbose_name='Papel'),
        ),
    ]
