# Generated by Django 6.0.2 on 2026-02-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_exito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidade de Êxito (%)')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('processos_similares', models.IntegerField(default=0, verbose_name='Processos Similares Encontrados')),
                ('vitórias_similares', models.IntegerField(default=0, verbose_name='Vitórias em Processos Similares')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_risco', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Análise de Risco',
                'verbose_name_plural': 'Análises de Risco',
            },
        ),
    ]
