# Generated by Django 4.2.28 on 2026-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_sugerido_id', models.IntegerField(help_text='ID do documento em jurisprudencia.Documento')),
                ('titulo_documento', models.CharField(max_length=300)),
                ('score_relevancia', models.FloatField(help_text='Pontuação de relevância 0.0-1.0')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Sugestão de Jurisprudência',
                'verbose_name_plural': 'Sugestões de Jurisprudência',
                'ordering': ['-score_relevancia'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_exito', models.FloatField(blank=True, help_text='0.0 a 1.0', null=True)),
                ('nivel_risco', models.CharField(blank=True, help_text='baixo/medio/alto', max_length=20, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('baseado_em_processos', models.IntegerField(default=0, help_text='Qtd de processos similares analisados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_risco', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Análise de Risco',
                'verbose_name_plural': 'Análises de Risco',
            },
        ),
    ]
