# Generated by Django 6.0.2 on 2026-02-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_preditiva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analiserisco',
            old_name='vitórias_similares',
            new_name='vitorias_similares',
        ),
    ]
