# Generated by Django 4.2.28 on 2026-02-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ia_preditiva', '0002_rename_vitórias_similares_analiserisco_vitorias_similares'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAEventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('integracao', 'Integração'), ('ia', 'IA'), ('financeiro', 'Financeiro'), ('prazos', 'Prazos')], default='backend', max_length=20, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('info', 'Info'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='alerta', max_length=20, verbose_name='Severidade')),
                ('mensagem', models.CharField(max_length=300, verbose_name='Mensagem')),
                ('rota', models.CharField(blank=True, max_length=255, verbose_name='Rota')),
                ('detalhes', models.JSONField(blank=True, null=True, verbose_name='Detalhes')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ia_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Evento de Monitoramento IA',
                'verbose_name_plural': 'Eventos de Monitoramento IA',
                'ordering': ['resolvido', '-criado_em'],
            },
        ),
    ]
