# Generated by Django 6.0.2 on 2026-02-23 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('decisao', 'Decisão Interlocutória'), ('tese', 'Tese Jurídica'), ('jurisprudencia', 'Jurisprudência Externa'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('tribunal', models.CharField(blank=True, max_length=100, verbose_name='Tribunal / Órgão')),
                ('conteudo', models.TextField(verbose_name='Conteúdo / Ementa')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='jurisprudencia/', verbose_name='Arquivo (PDF)')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Tags (separadas por vírgula)')),
                ('data_decisao', models.DateField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
                ('processo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_juridicos', to='processos.processo', verbose_name='Processo Vinculado')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
