# Generated by Django 4.2.28 on 2026-02-23 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('peticao', 'Petição'), ('decisao', 'Decisão Interlocutória'), ('tese', 'Tese Jurídica'), ('outro', 'Outro')], default='sentenca', max_length=20)),
                ('juiz', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_decisao', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, help_text='Ex: procedente, improcedente', max_length=50, null=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(help_text='Texto completo do documento para busca')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='jurisprudencia/')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.tipoprocesso')),
                ('vara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.vara')),
            ],
            options={
                'verbose_name': 'Documento Jurídico',
                'verbose_name_plural': 'Documentos Jurídicos',
                'ordering': ['-data_decisao'],
            },
        ),
    ]
