# Generated by Django 4.2.28 on 2026-02-24 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0002_lancamentoarquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('receber', 'A Receber'), ('pagar', 'A Pagar'), ('honorario', 'Honorário'), ('despesa', 'Despesa'), ('reembolso', 'Reembolso'), ('pagamento', 'Pagamento Recebido')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('banco', models.CharField(blank=True, max_length=120, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=30, verbose_name='Agência')),
                ('conta_numero', models.CharField(blank=True, max_length=40, verbose_name='Número da Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo Inicial')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_bancarias', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receber', 'Receber'), ('pagar', 'Pagar')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_financeiras', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'tipo', 'criado_por')},
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.contabancaria', verbose_name='Conta Bancária'),
        ),
    ]
