# Generated by Django 4.2.28 on 2026-02-26 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0006_processo_modulo_avancado'),
        ('financeiro', '0003_alter_lancamento_tipo_contabancaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('minutos', models.PositiveIntegerField(verbose_name='Minutos Trabalhados')),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor/Hora')),
                ('faturado_em', models.DateTimeField(blank=True, null=True, verbose_name='Faturado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos_tempo', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_tempo_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_tempo', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Apontamento de Tempo',
                'verbose_name_plural': 'Apontamentos de Tempo',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True, verbose_name='Número da Fatura')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Início do Período')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Fim do Período')),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('subtotal_tempo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal Tempo')),
                ('subtotal_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal Despesas')),
                ('subtotal_outros', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal Outros')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('gateway', models.CharField(choices=[('manual', 'Manual'), ('asaas', 'Asaas'), ('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], default='manual', max_length=20, verbose_name='Gateway')),
                ('online_status', models.CharField(choices=[('nao_gerado', 'Não Gerado'), ('aguardando', 'Aguardando'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='nao_gerado', max_length=20, verbose_name='Status de Recebimento Online')),
                ('online_external_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='ID Externo')),
                ('online_url', models.URLField(blank=True, null=True, verbose_name='URL de Pagamento')),
                ('data_recebimento_online', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento Online')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='faturado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faturado em'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='reembolsavel_cliente',
            field=models.BooleanField(default=False, verbose_name='Reembolsável ao Cliente'),
        ),
        migrations.CreateModel(
            name='RegraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título da Regra')),
                ('tipo_cobranca', models.CharField(choices=[('hora', 'Hora'), ('exito', 'Êxito'), ('pacote', 'Pacote'), ('recorrencia', 'Recorrência')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor/Hora')),
                ('percentual_exito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Êxito (%)')),
                ('valor_pacote', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Pacote')),
                ('valor_recorrente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Recorrente')),
                ('dia_vencimento_recorrencia', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de Vencimento da Recorrência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_cobranca', to='processos.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_cobranca_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_cobranca', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Regra de Cobrança',
                'verbose_name_plural': 'Regras de Cobrança',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('tempo', 'Tempo'), ('despesa', 'Despesa'), ('servico', 'Serviço'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apontamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fatura', to='financeiro.apontamentotempo', verbose_name='Apontamento de Tempo')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.fatura', verbose_name='Fatura')),
                ('lancamento_despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fatura_despesa', to='financeiro.lancamento', verbose_name='Despesa Vinculada')),
            ],
            options={
                'verbose_name': 'Item de Fatura',
                'verbose_name_plural': 'Itens de Fatura',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='lancamento_receber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_origem', to='financeiro.lancamento', verbose_name='Lançamento Financeiro'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='processos.processo', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='regra_cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='financeiro.regracobranca', verbose_name='Regra de Cobrança'),
        ),
        migrations.AddField(
            model_name='apontamentotempo',
            name='regra_cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos', to='financeiro.regracobranca', verbose_name='Regra de Cobrança'),
        ),
        migrations.AddField(
            model_name='apontamentotempo',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador', 'estagiario']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_tempo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
