# Generated by Django 4.2.28 on 2026-02-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0004_apontamentotempo_fatura_lancamento_faturado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentotempo',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['advogado', 'administrador', 'estagiario', 'assistente']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_tempo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
